/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/common/Avatar/Avatar.vue')['default']
    AxisX: typeof import('./src/components/charts/AxisX.vue')['default']
    AxisY: typeof import('./src/components/charts/AxisY.vue')['default']
    Background: typeof import('./src/components/common/Background/Background.vue')['default']
    BarChart: typeof import('./src/components/charts/BarChart.vue')['default']
    BaseCanvas: typeof import('./src/components/charts/BaseCanvas.vue')['default']
    Button: typeof import('./src/components/common/Button/Button.vue')['default']
    Card: typeof import('./src/components/common/Card/Card.vue')['default']
    ChartSync: typeof import('./src/components/charts/ChartSync.vue')['default']
    Column: typeof import('./src/components/layout/Column/Column.vue')['default']
    D3: typeof import('./src/components/charts/D3.vue')['default']
    EventStream: typeof import('./src/components/charts/EventStream.vue')['default']
    FixedBar: typeof import('./src/components/common/FixedBar/FixedBar.vue')['default']
    Form: typeof import('./src/components/common/Form/Form.vue')['default']
    H1: typeof import('./src/components/common/Typography/H1.vue')['default']
    Icon: typeof import('./src/components/common/Icon/Icon.vue')['default']
    Legend: typeof import('./src/components/charts/Legend.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    Logo: typeof import('./src/components/global/Logo.vue')['default']
    P: typeof import('./src/components/common/Typography/P.vue')['default']
    RAF: typeof import('./src/components/common/RAF.vue')['default']
    Root: typeof import('./src/components/global/Root.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./src/components/layout/Row/Row.vue')['default']
    Selection: typeof import('./src/components/charts/Selection.vue')['default']
    Shader: typeof import('./src/components/common/Shader.vue')['default']
    Stream: typeof import('./src/components/charts/Stream.vue')['default']
    TimeSeriesStream: typeof import('./src/components/charts/TimeSeriesStream.vue')['default']
    View: typeof import('./src/components/layout/View/View.vue')['default']
    XAxis: typeof import('./src/components/charts/XAxis.vue')['default']
  }
}
